version: '3' # specify docker-compose version

# Define the services/containers to be run
services:
  frontend:
    image: frontend
    build: ./frontend
    container_name: frontend

    volumes:
      - ./frontend/project:/home/project
    ports:
      - '8080:8080'
  backend:
    image: backend
    build: ./backend
    container_name: backend
    volumes:
      - ./backend/src:/usr/src
    ports:
      - '6060:6060'
    command: 'bash /usr/start.sh'
